[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc = "0.8.27"
optimizer = true
optimizer_runs = 200
remappings = [
    "risc0/=lib/risc0-ethereum/contracts/src/",
    "solady/=lib/solady/src/",
    # foundry is not able to detect this particular remapping for some reason...
    "openzeppelin/=lib/risc0-ethereum/lib/openzeppelin-contracts/",
    "@sp1-contracts/=lib/sp1-contracts/contracts/src/"
]

fs_permissions = [
    { access = "read", path = "../samples"},
    { access = "readwrite", path = "deployments" },
    { access = "read", path = "test" }
]